### ISSUE TITLE
Support integer status codes in responses

### ISSUE THREAD

**Issue by lornajane** [Nexmo/oas_parser#15]
Currently, this parser requires the response elements to be in quotes: `'200':`. OpenAPI supports them just being numbers: `200:` but this fails because to check if it's a success case we `match` a specific pattern in the string.

We should support numbers as keys in the responses section of an OpenAPI spec.

To test: remove the quotes around any OAS

**Comment by ahx** [comment]
In the current version (0.15.2), `OasParser::Definition.resolve` gives us an error: Could not find key 200, but it works when I change the status code in the spec file to an integer. 🤔

**Comment by ahx** [comment]
The current spec does not allow numbers as keys for response codes:

> This field MUST be enclosed in quotation marks (for example, "200") for compatibility between JSON and YAML.

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#patterned-fields-1

I think this issue can be closed.

**Comment by mheap** [comment]
Closing as the spec says that these keys must be quoted
