### ISSUE TITLE
Response schema does not support strings

### ISSUE THREAD

**Issue by lornajane** [Nexmo/oas_parser#16]
In an OpenAPI spec, none of the fields in a response is required.  This parser requires that within a response, the schema key is required and within that schema key the type can only be "array" or "object" - where as many other types are supported.

Example of what I wanted to write:
```
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type:  string
              example: "success"
```

This is valid in OpenAPI spec but causes this parser to error. It should also be possible to omit the schema tag completely.

**Comment by mheap** [comment]
Resolved in https://github.com/Nexmo/oas_parser/commit/168c3f74e228e1688cca86cd31f45680c4ea5fd5
