### ISSUE TITLE
Return nil or custom error when an object cannot be found

### ISSUE THREAD

**Issue by ahx** [Nexmo/oas_parser#17]
Currently oas_parser raises a StandardError when an object cannot be found:
```ruby
OasParser::Definition#path_by_path('/an_unknown_path')
# => StandardError: So such path exists
```

This make it a bit hard to use oas_parser if you want to react in a certain way if an object (path, method, status code) could not be found in the spec.

I think this could be improved by either

1. Return `nil` if an object cannot be found
or
2. Raise a custom error like `OasParser::NotFound`, `OasParser::PathNotFound`, `OasParser::CodeNotFound` or the like

That way consuming apps could easily react on it in a controlled way.

What do you think? – 1 , 2 or 3 (leave it like it is)

**Comment by ahx** [comment]
I think I would go with 1, because that way consumin apps don't have to handle exceptions for control flow. 1️⃣

**Comment by mheap** [comment]
@ahx Thanks for the issue + PR. I'd personally prefer option 2 as it would tell you exactly what's happening. Making the library return `nil` would lead to errors like `undefined method 'ABC' for nil:NilClass (NoMethodError)` when people try to interact with it. In this instance failing fast is preferable imo

Raising a custom error would also allow this to be merged without it being a breaking change as `OasParser::PathNotFound` could extend `StandardError`

**Comment by ahx** [comment]
Sounds like a plan!
