### ISSUE TITLE
doesn't resolve external references

### ISSUE THREAD

**Issue by MarioRuiz** [Nexmo/oas_parser#20]
It doesn't accept external references like:

`{"$ref"=>"examples/Snapshots_Update.json"}`

Only works when reference is "file:/xxxxxx"
According to https://swagger.io/docs/specification/using-ref/ should accept also 
`{"$ref"=>"examples/Snapshots_Update.json"}`

**Comment by rmosolgo** [comment]
It looks like this was fixed by #23, should it be closed?

**Comment by ahx** [comment]
I think this can be closed.
