### ISSUE TITLE
recurrent references not allowed

### ISSUE THREAD

**Issue by MarioRuiz** [Nexmo/oas_parser#24]
Using this open api 3 file: https://v2.namsor.com/NamSorAPIv2/api2/openapi.json
When recurrent references for example:

    "components": {
        "schemas": {
           "UserInfoOut": {
                "type": "object",
                "properties": {
                    "otherInfos": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/UserInfoOut"
                        }
                    }

**Comment by mheap** [comment]
Hey @MarioRuiz - how would you expect this to be handled? This would cause infinite recursion at the moment

**Comment by MarioRuiz** [comment]
@mheap maybe for those parsings that are not possible to be done, we should notify them and not parsing them but the rest

**Comment by mheap** [comment]
Sounds good. This isn't something we encounter but I'd be happy to receive a PR + tests
