### ISSUE TITLE
Parsing the `tags` field of the root OpenAPI document

### ISSUE THREAD

**Issue by j-a-m-l** [Nexmo/oas_parser#54]
As specified on [version 3.03](http://spec.openapis.org/oas/v3.0.3#openapi-object), an array of Tag objects, the `tags` field could be used on the root document object.

Currently, this field is completely ignored.

In case you're interested, I wouldn't mind to implement it myself.

**Comment by mheap** [comment]
Hey @j-a-m-l!

You can access the tags using `OasParser::Definition.raw['tags']` if you need access right now, but we'd also love a PR to add an actual object to help access them
