### ISSUE TITLE
Publish the API?

### ISSUE THREAD

**Issue by pmackay** [Nexmo/oas_parser#8]
Would it be possible to publish a set of generated API docs, so the full API can be seen? 

Alternatively listing each of the major elements of OAS and what properties of each are supported would be very helpful :-)

**Comment by mheap** [comment]
@pmackay Do you have any suggested tools to generate the API documentation? I can help with publishing, but I'm not too familiar with the ecosystem

**Comment by pmackay** [comment]
I think the simplest thing I had in mind was https://www.rubydoc.info/github/Nexmo/oas_parser/. You can add any github project to rubydoc.info and it generates the docs (so I tried it!). Click "About" on https://www.rubydoc.info/# to see the post-receive hook (not exactly sure how that's set).

**Comment by mheap** [comment]
That webhook's all configured now 👍
